### ISSUE TITLE
Colon instead of semi-colon in documentation example

### ISSUE THREAD

**Issue by erezschatz** [mstratman/Catalyst-View-XML-Feed#2]
```
sub rss : Local {
    my ($self, $c) = @_:
```

Would cause error is copy/pasted.

**Comment by mstratman** [comment]
Fixed, thanks! https://github.com/mstratman/Catalyst-View-XML-Feed/commit/c5cddb012d62a69ed6515eb9065fcd653a24dbed

Uploaded to cpan now.
